name: test
on: [ push ]
jobs:
  postgresql:
    runs-on: ubuntu-latest
    name: Test migrate up with postgres
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qyo}Mh{Bn&X[Ppc!dlsrG
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Check with version flag
        uses: ./
        with:
          database: postgres://postgres:qyo}Mh{Bn&X[Ppc!dlsrG@postgres:5432/database?sslmode=disable
          version: true

  sqlite3:
    runs-on: ubuntu-latest
    name: Test migrate up with sqlite3
    steps:
      - uses: actions/checkout@v3
      - name: Check with version flag
        uses: ./
        with:
          database: sqlite3://database.sqlite3.db
          version: true
